// Query TypeMap
import "@sanity/client";

/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: schema.json
export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type AssetLinkFile = {
  asset?: SanityFileAssetReference;
  media?: unknown; // Unable to locate the referenced type "media" in schema
  _type: "file";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Image1 = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "media1" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  caption?: string;
  credit?: string;
  alt?: string;
  _type: "image";
};

export type Youtube = {
  _type: "youtube";
  url?: string;
};

export type SomeLink = {
  _type: "someLink";
  title?:
    | "Bluesky"
    | "Facebook"
    | "Instagram"
    | "LinkedIn"
    | "Tiktok"
    | "Twitch"
    | "YouTube";
  href?: string;
};

export type SdgReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sdg";
};

export type SdgRef = {
  _type: "sdg-ref";
  sdg?: SdgReference;
};

export type Quiz = {
  _type: "quiz";
  question?: string;
  choices?: Array<
    {
      _key: string;
    } & Choice
  >;
};

export type PersonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "person";
};

export type People = {
  _type: "people";
  title?: string;
  members?: Array<{
    person?: PersonReference;
    title?: string;
    _key: string;
  }>;
  showContactInfo?: boolean;
  showDescription?: boolean;
};

export type Link = {
  _type: "link";
  title?: string;
  href?: string;
};

export type Lesson = {
  _type: "lesson";
  title?: string;
  slug?: Slug;
  description?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              href?: string;
              _type: "link";
              _key: string;
            }
          | {
              file?: AssetLinkFile;
              _type: "assetLink";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        caption?: string;
        credit?: string;
        alt?: string;
        position?: "floatRight";
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & DocumentLink)
    | ({
        _key: string;
      } & EventReference_2)
    | ({
        _key: string;
      } & People)
    | ({
        _key: string;
      } & Youtube)
    | ({
        _key: string;
      } & Audio)
    | ({
        _key: string;
      } & Quiz)
    | ({
        _key: string;
      } & Cta)
    | ({
        _key: string;
      } & SdgRef)
  >;
};

export type Expiration = {
  _type: "expiration";
  expiredAt?: string;
  explanation?: string;
};

export type EventReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "event";
};

export type EventReference_2 = EventReference;

export type Duration = {
  _type: "duration";
  start?: string;
  end?: string;
};

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type DocumentLink = PostReference | PageReference;

export type Cta = {
  _type: "cta";
  label?: string;
  href?: string;
  subtitle?: string;
  target?: "_self" | "_blank";
};

export type Choice = {
  _type: "choice";
  title?: string;
  isCorrect?: boolean;
};

export type Audio = {
  _type: "audio";
  url?: string;
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
};

export type Sdg = {
  _id: string;
  _type: "sdg";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  number?: number;
  name?: string;
  symbol?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: string;
  url?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Organization = {
  _id: string;
  _type: "organization";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  email?: string;
  phone?: string;
  url?: string;
  image?: Image1;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              href?: string;
              _type: "link";
              _key: string;
            }
          | {
              file?: AssetLinkFile;
              _type: "assetLink";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        caption?: string;
        credit?: string;
        alt?: string;
        position?: "floatRight";
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & DocumentLink)
    | ({
        _key: string;
      } & EventReference_2)
    | ({
        _key: string;
      } & People)
    | ({
        _key: string;
      } & Youtube)
    | ({
        _key: string;
      } & Audio)
    | ({
        _key: string;
      } & Quiz)
    | ({
        _key: string;
      } & Cta)
    | ({
        _key: string;
      } & SdgRef)
  >;
  active?: boolean;
  ssbCode?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              href?: string;
              _type: "link";
              _key: string;
            }
          | {
              file?: AssetLinkFile;
              _type: "assetLink";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        caption?: string;
        credit?: string;
        alt?: string;
        position?: "floatRight";
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & DocumentLink)
    | ({
        _key: string;
      } & EventReference_2)
    | ({
        _key: string;
      } & People)
    | ({
        _key: string;
      } & Youtube)
    | ({
        _key: string;
      } & Audio)
    | ({
        _key: string;
      } & Quiz)
    | ({
        _key: string;
      } & Cta)
    | ({
        _key: string;
      } & SdgRef)
  >;
  lessons?: Array<
    {
      _key: string;
    } & Lesson
  >;
  image?: Image1;
  active?: boolean;
  sortOrder?: number;
};

export type CountyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "county";
};

export type Topic = {
  _id: string;
  _type: "topic";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  county?: CountyReference;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              href?: string;
              _type: "link";
              _key: string;
            }
          | {
              file?: AssetLinkFile;
              _type: "assetLink";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        caption?: string;
        credit?: string;
        alt?: string;
        position?: "floatRight";
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & DocumentLink)
    | ({
        _key: string;
      } & EventReference_2)
    | ({
        _key: string;
      } & People)
    | ({
        _key: string;
      } & Youtube)
    | ({
        _key: string;
      } & Audio)
    | ({
        _key: string;
      } & Quiz)
    | ({
        _key: string;
      } & Cta)
    | ({
        _key: string;
      } & SdgRef)
  >;
  image?: Image1;
  contacts?: Array<
    {
      _key: string;
    } & PersonReference
  >;
  active?: boolean;
};

export type County = {
  _id: string;
  _type: "county";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              href?: string;
              _type: "link";
              _key: string;
            }
          | {
              file?: AssetLinkFile;
              _type: "assetLink";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        caption?: string;
        credit?: string;
        alt?: string;
        position?: "floatRight";
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & DocumentLink)
    | ({
        _key: string;
      } & EventReference_2)
    | ({
        _key: string;
      } & People)
    | ({
        _key: string;
      } & Youtube)
    | ({
        _key: string;
      } & Audio)
    | ({
        _key: string;
      } & Quiz)
    | ({
        _key: string;
      } & Cta)
    | ({
        _key: string;
      } & SdgRef)
  >;
  image?: Image1;
  contacts?: Array<
    {
      _key: string;
    } & PersonReference
  >;
  active?: boolean;
  countyCode?: Array<string>;
  locale?: "nb-NO" | "nn-NO" | "en-US";
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              href?: string;
              _type: "link";
              _key: string;
            }
          | {
              file?: AssetLinkFile;
              _type: "assetLink";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        caption?: string;
        credit?: string;
        alt?: string;
        position?: "floatRight";
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & DocumentLink)
    | ({
        _key: string;
      } & EventReference_2)
    | ({
        _key: string;
      } & People)
    | ({
        _key: string;
      } & Youtube)
    | ({
        _key: string;
      } & Audio)
    | ({
        _key: string;
      } & Quiz)
    | ({
        _key: string;
      } & Cta)
    | ({
        _key: string;
      } & SdgRef)
  >;
  contacts?: Array<
    {
      _key: string;
    } & PersonReference
  >;
};

export type TopicReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "topic";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  docType?:
    | "nyhet"
    | "pm"
    | "historie"
    | "protokoll"
    | "rapport"
    | "h\xF8ringssvar"
    | "veileder";
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    credit?: string;
    alt?: string;
    _type: "image";
  };
  publishedAt?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              href?: string;
              _type: "link";
              _key: string;
            }
          | {
              file?: AssetLinkFile;
              _type: "assetLink";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        caption?: string;
        credit?: string;
        alt?: string;
        position?: "floatRight";
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & DocumentLink)
    | ({
        _key: string;
      } & EventReference_2)
    | ({
        _key: string;
      } & People)
    | ({
        _key: string;
      } & Youtube)
    | ({
        _key: string;
      } & Audio)
    | ({
        _key: string;
      } & Quiz)
    | ({
        _key: string;
      } & Cta)
    | ({
        _key: string;
      } & SdgRef)
  >;
  attachments?: Array<{
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
    _key: string;
  }>;
  remoteUrl?: string;
  eventReference?: EventReference;
  relevance?: ArrayOf<CountyReference | TopicReference>;
  expiration?: Expiration;
  locale?: "nb-NO" | "nn-NO" | "en-US";
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  duration?: Duration;
  location?: {
    name?: string;
    address?: string;
  };
  ownEvent?: boolean;
  registrationUrl?: string;
  registrationDueDate?: string;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  position?: string;
  organization?: string;
  email?: string;
  phone?: string;
  image?: Image1;
  description?: string;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  officeAddress?: string;
  postalAddress?: string;
  email?: string;
  phone?: string;
  shortcuts?: Array<
    {
      _key: string;
    } & Link
  >;
  about?: Array<
    {
      _key: string;
    } & Link
  >;
  some?: Array<
    {
      _key: string;
    } & SomeLink
  >;
  contacts?: Array<
    {
      _key: string;
    } & PersonReference
  >;
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  announcement?: {
    emoji?: string;
    title?: string;
    href?: string;
  };
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityFileAssetReference
  | AssetLinkFile
  | SanityImageAssetReference
  | Image1
  | Youtube
  | SomeLink
  | SdgReference
  | SdgRef
  | Quiz
  | PersonReference
  | People
  | Link
  | Lesson
  | Expiration
  | EventReference
  | EventReference_2
  | Duration
  | PostReference
  | PageReference
  | DocumentLink
  | Cta
  | Choice
  | Audio
  | Sdg
  | SanityImageCrop
  | SanityImageHotspot
  | Organization
  | Slug
  | Course
  | CountyReference
  | Topic
  | County
  | Page
  | TopicReference
  | Post
  | Event
  | Person
  | Settings
  | Home
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: postsByReferenceQuery
// Query: *[    (_type == "post") &&     defined(image) &&    (!defined($ref) || references($ref)) &&    (      (defined(expiration.expiredAt) && dateTime(now()) < dateTime(expiration.expiredAt)) ||       (!defined(expiration.expiredAt) && dateTime(now()) < dateTime(now()) + 31556926)    )  ] | order(publishedAt desc) [0...6] {    _id,    _type,    docType,    title,    description,    image,    publishedAt,    _updatedAt,    "slug": slug.current,    "relevance": relevance[] -> {      _id,      _type,      "title": coalesce(name, title),      "slug": slug.current,    },  }
export type PostsByReferenceQueryResult = Array<{
  _id: string;
  _type: "post";
  docType:
    | "historie"
    | "h\xF8ringssvar"
    | "nyhet"
    | "pm"
    | "protokoll"
    | "rapport"
    | "veileder"
    | null;
  title: string | null;
  description: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    credit?: string;
    alt?: string;
    _type: "image";
  } | null;
  publishedAt: string | null;
  _updatedAt: string;
  slug: string | null;
  relevance: Array<
    | {
        _id: string;
        _type: "county";
        title: string | null;
        slug: string | null;
      }
    | {
        _id: string;
        _type: "topic";
        title: string | null;
        slug: string | null;
      }
  > | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: searchPostsQuery
// Query: *[    (_type == "post") &&    (!defined($docTypes) || docType in $docTypes) &&    (!defined($years) || string::split(publishedAt, "-")[0] in $years) &&    (!defined($refs) || references($refs)) &&    (!defined($q) || ([title, description, pt::text(body)] match $q)) &&    (!defined($lastPublishedAt) || (publishedAt < $lastPublishedAt || (publishedAt == $lastPublishedAt && _id < $lastId)))  ] | order(publishedAt desc) [0...30] {    _id,    _type,    docType,    title,    description,    image,    publishedAt,    _updatedAt,    "slug": slug.current,    "relevance": relevance[] -> {      _id,      _type,      "title": coalesce(name, title),      "slug": slug.current,    },  }
export type SearchPostsQueryResult = Array<{
  _id: string;
  _type: "post";
  docType:
    | "historie"
    | "h\xF8ringssvar"
    | "nyhet"
    | "pm"
    | "protokoll"
    | "rapport"
    | "veileder"
    | null;
  title: string | null;
  description: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    credit?: string;
    alt?: string;
    _type: "image";
  } | null;
  publishedAt: string | null;
  _updatedAt: string;
  slug: string | null;
  relevance: Array<
    | {
        _id: string;
        _type: "county";
        title: string | null;
        slug: string | null;
      }
    | {
        _id: string;
        _type: "topic";
        title: string | null;
        slug: string | null;
      }
  > | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: postBySlugQuery
// Query: *[_type == "post" && slug.current == $slug][0] {    _id,    docType,    title,    description,    image,    publishedAt,    _updatedAt,    "slug": slug.current,    body,    "toc": body[style == "h2"],    "attachments": attachments[].asset -> { _id, assetId, originalFilename, mimeType, size },    expiration,    remoteUrl,    locale,    relevance,  }
export type PostBySlugQueryResult = {
  _id: string;
  docType:
    | "historie"
    | "h\xF8ringssvar"
    | "nyhet"
    | "pm"
    | "protokoll"
    | "rapport"
    | "veileder"
    | null;
  title: string | null;
  description: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    credit?: string;
    alt?: string;
    _type: "image";
  } | null;
  publishedAt: string | null;
  _updatedAt: string;
  slug: string | null;
  body: Array<
    | ({
        _key: string;
      } & Audio)
    | ({
        _key: string;
      } & Cta)
    | ({
        _key: string;
      } & DocumentLink)
    | ({
        _key: string;
      } & EventReference_2)
    | ({
        _key: string;
      } & People)
    | ({
        _key: string;
      } & Quiz)
    | ({
        _key: string;
      } & SdgRef)
    | ({
        _key: string;
      } & Youtube)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              file?: AssetLinkFile;
              _type: "assetLink";
              _key: string;
            }
          | {
              href?: string;
              _type: "link";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        caption?: string;
        credit?: string;
        alt?: string;
        position?: "floatRight";
        _type: "image";
        _key: string;
      }
  > | null;
  toc: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style: "h2";
    listItem?: "bullet" | "number";
    markDefs?: Array<
      | {
          file?: AssetLinkFile;
          _type: "assetLink";
          _key: string;
        }
      | {
          href?: string;
          _type: "link";
          _key: string;
        }
    >;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  attachments: Array<{
    _id: string;
    assetId: string | null;
    originalFilename: string | null;
    mimeType: string | null;
    size: number | null;
  } | null> | null;
  expiration: Expiration | null;
  remoteUrl: string | null;
  locale: "en-US" | "nb-NO" | "nn-NO" | null;
  relevance: ArrayOf<CountyReference | TopicReference> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: pageBySlugQuery
// Query: *[_type == "page" && slug.current == $slug][0] {    _id,    title,    description,    _updatedAt,    "slug": slug.current,    body,    "toc": body[style == "h2"],    contacts,    locale,  }
export type PageBySlugQueryResult = {
  _id: string;
  title: string | null;
  description: string | null;
  _updatedAt: string;
  slug: string | null;
  body: Array<
    | ({
        _key: string;
      } & Audio)
    | ({
        _key: string;
      } & Cta)
    | ({
        _key: string;
      } & DocumentLink)
    | ({
        _key: string;
      } & EventReference_2)
    | ({
        _key: string;
      } & People)
    | ({
        _key: string;
      } & Quiz)
    | ({
        _key: string;
      } & SdgRef)
    | ({
        _key: string;
      } & Youtube)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              file?: AssetLinkFile;
              _type: "assetLink";
              _key: string;
            }
          | {
              href?: string;
              _type: "link";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        caption?: string;
        credit?: string;
        alt?: string;
        position?: "floatRight";
        _type: "image";
        _key: string;
      }
  > | null;
  toc: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style: "h2";
    listItem?: "bullet" | "number";
    markDefs?: Array<
      | {
          file?: AssetLinkFile;
          _type: "assetLink";
          _key: string;
        }
      | {
          href?: string;
          _type: "link";
          _key: string;
        }
    >;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  contacts: Array<
    {
      _key: string;
    } & PersonReference
  > | null;
  locale: null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: documentLinkByIdQuery
// Query: *[_type in ["page", "post"] && _id == $id][0] {    _type,    title,    description,    "slug": slug.current,    image,  }
export type DocumentLinkByIdQueryResult =
  | {
      _type: "page";
      title: string | null;
      description: string | null;
      slug: string | null;
      image: null;
    }
  | {
      _type: "post";
      title: string | null;
      description: string | null;
      slug: string | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        caption?: string;
        credit?: string;
        alt?: string;
        _type: "image";
      } | null;
    }
  | null;

// Source: sanity/lib/queries.ts
// Variable: tagByIdQuery
// Query: *[_type in ["county", "topic"] && _id == $id][0] {    _type,    "title": coalesce(name, title),    "slug": slug.current,  }
export type TagByIdQueryResult =
  | {
      _type: "county";
      title: string | null;
      slug: string | null;
    }
  | {
      _type: "topic";
      title: string | null;
      slug: string | null;
    }
  | null;

// Source: sanity/lib/queries.ts
// Variable: allActiveSfQuery
// Query: *[_type == "organization" && active == true && defined(ssbCode) && defined(slug)][]{    _id,    "title": name,    "slug": slug.current,    description,    image,  } | order(title asc)
export type AllActiveSfQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  image: Image1 | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: allActiveCountiesQuery
// Query: *[_type == "county" && active == true][]{    _id,    "title": name,    "slug": slug.current,    description,    image,  } | order(title asc)
export type AllActiveCountiesQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  image: Image1 | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: countyBySlugQuery
// Query: *[_type == "county" && slug.current == $slug][0] {    _id,    "title": name,    "slug": slug.current,    description,    image,    body,    contacts,    countyCode,    locale,  }
export type CountyBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  image: Image1 | null;
  body: Array<
    | ({
        _key: string;
      } & Audio)
    | ({
        _key: string;
      } & Cta)
    | ({
        _key: string;
      } & DocumentLink)
    | ({
        _key: string;
      } & EventReference_2)
    | ({
        _key: string;
      } & People)
    | ({
        _key: string;
      } & Quiz)
    | ({
        _key: string;
      } & SdgRef)
    | ({
        _key: string;
      } & Youtube)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              file?: AssetLinkFile;
              _type: "assetLink";
              _key: string;
            }
          | {
              href?: string;
              _type: "link";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        caption?: string;
        credit?: string;
        alt?: string;
        position?: "floatRight";
        _type: "image";
        _key: string;
      }
  > | null;
  contacts: Array<
    {
      _key: string;
    } & PersonReference
  > | null;
  countyCode: Array<string> | null;
  locale: "en-US" | "nb-NO" | "nn-NO" | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: allActiveCoursesQuery
// Query: *[_type == "course" && active == true][]{    _id,    title,    "slug": slug.current,    description,    image,    "lessons": lessons[].slug.current,  } | order(sortOrder asc, title asc)
export type AllActiveCoursesQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  image: Image1 | null;
  lessons: Array<string | null> | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: calendarEntryByIdQuery
// Query: *[_type == "event" && _id == $id][0] {    _id,    title,    description,    duration,    location,    ownEvent,    registrationUrl,    registrationDueDate,  }
export type CalendarEntryByIdQueryResult = {
  _id: string;
  title: string | null;
  description: string | null;
  duration: Duration | null;
  location: {
    name?: string;
    address?: string;
  } | null;
  ownEvent: boolean | null;
  registrationUrl: string | null;
  registrationDueDate: string | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: calendarEntriesQuery
// Query: *[_type == "event" &&    (!defined($year) || string::split(duration.start, "-")[0] == $year) &&    (defined($year) || dateTime(now()) < dateTime(coalesce(duration.end, duration.start)))  ][]{    _id,    title,    description,    duration,    location,    ownEvent,    registrationUrl,    registrationDueDate,    "relatedPost": *[_type=='post' && references(^._id)] | order(publishedAt desc) [0] {      _type,      title,      description,      "slug": slug.current,      image    }   } | order(duration.start asc, duration.end asc)
export type CalendarEntriesQueryResult = Array<{
  _id: string;
  title: string | null;
  description: string | null;
  duration: Duration | null;
  location: {
    name?: string;
    address?: string;
  } | null;
  ownEvent: boolean | null;
  registrationUrl: string | null;
  registrationDueDate: string | null;
  relatedPost: {
    _type: "post";
    title: string | null;
    description: string | null;
    slug: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      credit?: string;
      alt?: string;
      _type: "image";
    } | null;
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: courseBySlugQuery
// Query: *[_type == "course" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    description,    image,    body,    lessons[] {      title,      "slug": slug.current,      description,      body,    },  }
export type CourseBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  image: Image1 | null;
  body: Array<
    | ({
        _key: string;
      } & Audio)
    | ({
        _key: string;
      } & Cta)
    | ({
        _key: string;
      } & DocumentLink)
    | ({
        _key: string;
      } & EventReference_2)
    | ({
        _key: string;
      } & People)
    | ({
        _key: string;
      } & Quiz)
    | ({
        _key: string;
      } & SdgRef)
    | ({
        _key: string;
      } & Youtube)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              file?: AssetLinkFile;
              _type: "assetLink";
              _key: string;
            }
          | {
              href?: string;
              _type: "link";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        caption?: string;
        credit?: string;
        alt?: string;
        position?: "floatRight";
        _type: "image";
        _key: string;
      }
  > | null;
  lessons: Array<{
    title: string | null;
    slug: string | null;
    description: string | null;
    body: Array<
      | ({
          _key: string;
        } & Audio)
      | ({
          _key: string;
        } & Cta)
      | ({
          _key: string;
        } & DocumentLink)
      | ({
          _key: string;
        } & EventReference_2)
      | ({
          _key: string;
        } & People)
      | ({
          _key: string;
        } & Quiz)
      | ({
          _key: string;
        } & SdgRef)
      | ({
          _key: string;
        } & Youtube)
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "blockquote" | "h2" | "h3" | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<
            | {
                file?: AssetLinkFile;
                _type: "assetLink";
                _key: string;
              }
            | {
                href?: string;
                _type: "link";
                _key: string;
              }
          >;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          caption?: string;
          credit?: string;
          alt?: string;
          position?: "floatRight";
          _type: "image";
          _key: string;
        }
    > | null;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: allActiveTopicsQuery
// Query: *[_type == "topic" && active == true][]{    _id,    title,    "slug": slug.current,    description,    image,  } | order(title asc)
export type AllActiveTopicsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  image: Image1 | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: topicBySlugQuery
// Query: *[_type == "topic" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    description,    _updatedAt,    image,    body,    "toc": body[style == "h2"],    contacts,    locale,  }
export type TopicBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  _updatedAt: string;
  image: Image1 | null;
  body: Array<
    | ({
        _key: string;
      } & Audio)
    | ({
        _key: string;
      } & Cta)
    | ({
        _key: string;
      } & DocumentLink)
    | ({
        _key: string;
      } & EventReference_2)
    | ({
        _key: string;
      } & People)
    | ({
        _key: string;
      } & Quiz)
    | ({
        _key: string;
      } & SdgRef)
    | ({
        _key: string;
      } & Youtube)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              file?: AssetLinkFile;
              _type: "assetLink";
              _key: string;
            }
          | {
              href?: string;
              _type: "link";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        caption?: string;
        credit?: string;
        alt?: string;
        position?: "floatRight";
        _type: "image";
        _key: string;
      }
  > | null;
  toc: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style: "h2";
    listItem?: "bullet" | "number";
    markDefs?: Array<
      | {
          file?: AssetLinkFile;
          _type: "assetLink";
          _key: string;
        }
      | {
          href?: string;
          _type: "link";
          _key: string;
        }
    >;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  contacts: Array<
    {
      _key: string;
    } & PersonReference
  > | null;
  locale: null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: personByIdQuery
// Query: *[_type == "person" && _id == $id][0] {    _id,    name,    position,    image,    email,    phone,    description,  }
export type PersonByIdQueryResult = {
  _id: string;
  name: string | null;
  position: string | null;
  image: Image1 | null;
  email: string | null;
  phone: string | null;
  description: string | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: sdgByIdQuery
// Query: *[_type == "sdg" && _id == $id][0] {    _id,    number,    name,    symbol,    description,    url,  }
export type SdgByIdQueryResult = {
  _id: string;
  number: number | null;
  name: string | null;
  symbol: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  description: string | null;
  url: string | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: homeQuery
// Query: *[_type == "home"][0]{  title,  description,  announcement{ emoji, title, href },}
export type HomeQueryResult = {
  title: string | null;
  description: string | null;
  announcement: {
    emoji: string | null;
    title: string | null;
    href: string | null;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]{  postalAddress,  officeAddress,  email,  phone,   about[]{ title, href },  shortcuts[]{ title, href },  some[]{ title, href },  contacts,}
export type SettingsQueryResult = {
  postalAddress: string | null;
  officeAddress: string | null;
  email: string | null;
  phone: string | null;
  about: Array<{
    title: string | null;
    href: string | null;
  }> | null;
  shortcuts: Array<{
    title: string | null;
    href: string | null;
  }> | null;
  some: Array<{
    title:
      | "Bluesky"
      | "Facebook"
      | "Instagram"
      | "LinkedIn"
      | "Tiktok"
      | "Twitch"
      | "YouTube"
      | null;
    href: string | null;
  }> | null;
  contacts: Array<
    {
      _key: string;
    } & PersonReference
  > | null;
} | null;

declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[\n    (_type == "post") && \n    defined(image) &&\n    (!defined($ref) || references($ref)) &&\n    (\n      (defined(expiration.expiredAt) && dateTime(now()) < dateTime(expiration.expiredAt)) || \n      (!defined(expiration.expiredAt) && dateTime(now()) < dateTime(now()) + 31556926)\n    )\n  ] | order(publishedAt desc) [0...6] {\n    _id,\n    _type,\n    docType,\n    title,\n    description,\n    image,\n    publishedAt,\n    _updatedAt,\n    "slug": slug.current,\n    "relevance": relevance[] -> {\n      _id,\n      _type,\n      "title": coalesce(name, title),\n      "slug": slug.current,\n    },\n  }\n': PostsByReferenceQueryResult;
    '\n  *[\n    (_type == "post") &&\n    (!defined($docTypes) || docType in $docTypes) &&\n    (!defined($years) || string::split(publishedAt, "-")[0] in $years) &&\n    (!defined($refs) || references($refs)) &&\n    (!defined($q) || ([title, description, pt::text(body)] match $q)) &&\n    (!defined($lastPublishedAt) || (publishedAt < $lastPublishedAt || (publishedAt == $lastPublishedAt && _id < $lastId)))\n  ] | order(publishedAt desc) [0...30] {\n    _id,\n    _type,\n    docType,\n    title,\n    description,\n    image,\n    publishedAt,\n    _updatedAt,\n    "slug": slug.current,\n    "relevance": relevance[] -> {\n      _id,\n      _type,\n      "title": coalesce(name, title),\n      "slug": slug.current,\n    },\n  }\n': SearchPostsQueryResult;
    '\n  *[_type == "post" && slug.current == $slug][0] {\n    _id,\n    docType,\n    title,\n    description,\n    image,\n    publishedAt,\n    _updatedAt,\n    "slug": slug.current,\n    body,\n    "toc": body[style == "h2"],\n    "attachments": attachments[].asset -> { _id, assetId, originalFilename, mimeType, size },\n    expiration,\n    remoteUrl,\n    locale,\n    relevance,\n  }\n': PostBySlugQueryResult;
    '\n  *[_type == "page" && slug.current == $slug][0] {\n    _id,\n    title,\n    description,\n    _updatedAt,\n    "slug": slug.current,\n    body,\n    "toc": body[style == "h2"],\n    contacts,\n    locale,\n  }\n': PageBySlugQueryResult;
    '\n  *[_type in ["page", "post"] && _id == $id][0] {\n    _type,\n    title,\n    description,\n    "slug": slug.current,\n    image,\n  }\n': DocumentLinkByIdQueryResult;
    '\n  *[_type in ["county", "topic"] && _id == $id][0] {\n    _type,\n    "title": coalesce(name, title),\n    "slug": slug.current,\n  }\n': TagByIdQueryResult;
    '\n  *[_type == "organization" && active == true && defined(ssbCode) && defined(slug)][]{\n    _id,\n    "title": name,\n    "slug": slug.current,\n    description,\n    image,\n  } | order(title asc)\n': AllActiveSfQueryResult;
    '\n  *[_type == "county" && active == true][]{\n    _id,\n    "title": name,\n    "slug": slug.current,\n    description,\n    image,\n  } | order(title asc)\n': AllActiveCountiesQueryResult;
    '\n  *[_type == "county" && slug.current == $slug][0] {\n    _id,\n    "title": name,\n    "slug": slug.current,\n    description,\n    image,\n    body,\n    contacts,\n    countyCode,\n    locale,\n  }\n': CountyBySlugQueryResult;
    '\n  *[_type == "course" && active == true][]{\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    image,\n    "lessons": lessons[].slug.current,\n  } | order(sortOrder asc, title asc)\n': AllActiveCoursesQueryResult;
    '\n  *[_type == "event" && _id == $id][0] {\n    _id,\n    title,\n    description,\n    duration,\n    location,\n    ownEvent,\n    registrationUrl,\n    registrationDueDate,\n  }\n': CalendarEntryByIdQueryResult;
    '\n  *[_type == "event" &&\n    (!defined($year) || string::split(duration.start, "-")[0] == $year) &&\n    (defined($year) || dateTime(now()) < dateTime(coalesce(duration.end, duration.start)))\n  ][]{\n    _id,\n    title,\n    description,\n    duration,\n    location,\n    ownEvent,\n    registrationUrl,\n    registrationDueDate,\n    "relatedPost": *[_type==\'post\' && references(^._id)] | order(publishedAt desc) [0] {\n      _type,\n      title,\n      description,\n      "slug": slug.current,\n      image\n    } \n  } | order(duration.start asc, duration.end asc)\n': CalendarEntriesQueryResult;
    '\n  *[_type == "course" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    image,\n    body,\n    lessons[] {\n      title,\n      "slug": slug.current,\n      description,\n      body,\n    },\n  }\n': CourseBySlugQueryResult;
    '\n  *[_type == "topic" && active == true][]{\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    image,\n  } | order(title asc)\n': AllActiveTopicsQueryResult;
    '\n  *[_type == "topic" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    _updatedAt,\n    image,\n    body,\n    "toc": body[style == "h2"],\n    contacts,\n    locale,\n  }\n': TopicBySlugQueryResult;
    '\n  *[_type == "person" && _id == $id][0] {\n    _id,\n    name,\n    position,\n    image,\n    email,\n    phone,\n    description,\n  }\n': PersonByIdQueryResult;
    '\n  *[_type == "sdg" && _id == $id][0] {\n    _id,\n    number,\n    name,\n    symbol,\n    description,\n    url,\n  }\n': SdgByIdQueryResult;
    '*[_type == "home"][0]{\n  title,\n  description,\n  announcement{ emoji, title, href },\n}': HomeQueryResult;
    '*[_type == "settings"][0]{\n  postalAddress,\n  officeAddress,\n  email,\n  phone, \n  about[]{ title, href },\n  shortcuts[]{ title, href },\n  some[]{ title, href },\n  contacts,\n}': SettingsQueryResult;
  }
}
